name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the OS to run on

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (if you are using Python)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Use your language-specific dependencies

      - name: Run tests
        run: |
          python -m unittest discover  # Run tests using your test framework (unittest, pytest, etc.)
          
      - name: Upload test results (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/*.xml  # Path to test results if you want to save them
